a = input ('digite algo: ')
print ('que legal o titulo primitivo desse valor é', type(a))
print ('é um numero?', a.isnumeric())   
print ('é alfabetico?', a.isalpha())
print ('é alpfanumerico?', a.isalnum())
print ('esta em maiucsulas?', a.isupper())
print ('esta em minusculas?', a.islower())
print ('esta capitalizada?' , a.istitle())